'use strict'

const Schema = use('Schema')

class AdmissionsSchema extends Schema {
  up () {
    this.create('admissions', (table) => {
      table.increments('id')
      table.timestamps()
      table.string('Adresa_trvalého_pobytu')
      table.string('Alt_pr_1')
      table.string('Alternatívny_program_1')
      table.decimal('Body')
      table.decimal('Body_celkom')
      table.string('Druh_SŠ')
      table.string('E-mail')
      table.string('Et')
      table.string('Fakulta')
      table.string('Forma')
      table.string('Forma_1')
      table.string('Kompl')
      table.string('Kont_adr_-_pozn')
      table.string('Kont_adresa_-_obec')
      table.string('Kont_adresa_-_okres')
      table.string('Kont_adresa_-_ulica')
      table.string('Kont_adresa_-_ulica_1')
      table.string('Kont_adresa_-_štát')
      table.string('Kontaktná_adresa')
      table.string('Kontaktná_adresa_-_obec')
      table.string('Kontaktný_tel')
      table.string('Maturita')
      table.integer('Maturita_1')
      table.string('Meno')
      table.string('Metóda')
      table.string('Miesto_narodenia')
      table.string('Miesto_výučby')
      table.string('Modifikácia_PK')
      table.string('Najvyššie_dosiahnuté_vzdelanie')
      table.string('Narodenie')
      table.string('Občianstvo')
      table.integer('Odbor_SŠ')
      table.string('Odbor_na_SŠ')
      table.string('Odkiaľ_sa_hlási')
      table.string('Odvolanie')
      table.string('PSČ')
      table.string('PSČ_1')
      table.string('Pohlavie')
      table.integer('Por')
      table.string('Používateľ_(podľa_RČ)')
      table.string('Prevedené')
      table.string('Priemer_SŠ')
      table.string('Priemer_SŠ_1')
      table.string('Priezvisko')
      table.string('Prijatie_na_program')
      table.string('Prijatie_na_program_1')
      table.string('Prijaté')
      table.string('Program')
      table.string('Program_1')
      table.string('Program_2')
      table.string('Reg_č')
      table.string('Rodné_číslo')
      table.integer('Rozh')
      table.string('Rozhodnutie_o_prijatí')
      table.string('Stav')
      table.string('Stredná_škola')
      table.string('Stredná_škola_(adresa)')
      table.string('Stredná_škola_1')
      table.string('Súhlas_ZS')
      table.integer('SŠ_(kód)')
      table.string('Trv_pobyt_-_obec')
      table.string('Trv_pobyt_-_okres')
      table.string('Trv_pobyt_-_pozn')
      table.string('Trv_pobyt_-_ulica')
      table.string('Trv_pobyt_-_ulica_1')
      table.string('Trv_pobyt_-_štát')
      table.string('Trvalý_pobyt_-_obec')
      table.string('Zapl')
      table.integer('č_d')
      table.integer('č_d_1')
      table.string('Študijný_odbor')
      table.string('Štúdium')
    })
  }

  down () {
    this.drop('admissions')
  }
}

module.exports = AdmissionsSchema
